### ISSUE TITLE
tock-react-kit is not loading

### ISSUE THREAD

**Issue by AICHOUN-C** [theopenconversationkit/tock-react-kit#157]
Hello,

There seems to be an issue with the quick start of tock react kit.
Until Moday it was working.

Thanks
![image](https://github.com/theopenconversationkit/tock-react-kit/assets/47673928/421ca484-39a7-4467-87c3-631d56ed7c25)

**Comment by AICHOUN-C** [comment]
I'm having this issue on an angular application :
![image](https://github.com/theopenconversationkit/tock-react-kit/assets/47673928/22876d66-dc19-4417-ad1a-90e5748b2e78)

**Comment by Fabilin** [comment]
Are you using the `latest` version? I believe there is an issue that will be fixed by #156, but in the meantime you should be able to set the version to `22.9.0` to get back to the last working state.

**Comment by AICHOUN-C** [comment]
Are you sure about the 22.9.0 version?
![image](https://github.com/theopenconversationkit/tock-react-kit/assets/47673928/e1dcb431-e221-4e4e-850e-4798f4f5e00a)

**Comment by Fabilin** [comment]
Also, you need to update Emotion to version 11 for the package to work now.

**Comment by AICHOUN-C** [comment]
Hello @Fabilin,
Do you have a sample exemple that works with tock-react-kit 23.9.1?
I have some issues when i try to upgrade emotion to 11.
Thanks
![image](https://github.com/theopenconversationkit/tock-react-kit/assets/47673928/240e5625-4090-40b7-8a31-4fc914a3e37e)

**Comment by Fabilin** [comment]
Yes, Emotion changed its packages for version 11. To save yourselves some time, I would advise waiting for #162 to be merged (hopefully this week), which will greatly simplify the Quick Start process.
