### ISSUE TITLE
Document sse feature

### ISSUE THREAD

**Issue by Tiska** [theopenconversationkit/tock-react-kit#24]
Add doc for the new sse feature.

**Comment by vsct-jburet** [comment]
Should be nice also to not avec this sse error on https://doc.tock.ai/fr/ ;)

**Comment by francoisno** [comment]
There is some documentation added in v21.9.0: https://github.com/theopenconversationkit/tock-react-kit#sse

I close the issue for now - unless someone adds details about expected topics to cover.
