### ISSUE TITLE
tock-react-kit third arguments 'referralParameter'

### ISSUE THREAD

**Issue by Haitamchaoui** [theopenconversationkit/tock-react-kit#65]
the third argument 'referralParameter' for styling the chat is ignored, and all we have is the default style chat  in black and white.
please test the exemple in repository. and if we can have a project exemple it will be very helpful.

**Comment by francoisno** [comment]
Hello @Haitamchaoui have you been able to customize the styling?
After the _referralParameter_, one can provide styling options as a 4th parameter. E.g.:

    TockReact.renderChat(
        document.getElementById('chat'),
        'https://demo-bot.tock.ai/io/xxxxxxxxx',
        'referralParameter',
        { overrides: { chat: 'background-color: lightgreen;' } }
    );
