### ISSUE TITLE
New npm release planned ?

### ISSUE THREAD

**Issue by MikaFima** [theopenconversationkit/tock-react-kit#66]
Hi guys,

The last release on npm were done long time ago, and I love the refacto of the Chat component.
As we are using this component exploded, this will helps us a lot.

Thank guys, and good work :+1:

**Comment by elebescond** [comment]
Ok we can do a release next week

**Comment by MikaFima** [comment]
Ho, nice, thank you

**Comment by elebescond** [comment]
https://www.npmjs.com/package/tock-react-kit/v/20.9.1
