### ISSUE TITLE
readableColor unknown

### ISSUE THREAD

**Issue by msansen-esncf** [theopenconversationkit/tock-react-kit#68]
Hi, 

I got a message in console while tring to use example from github readme: and webpage stay empty

![image](https://user-images.githubusercontent.com/60747886/120802223-7b2d1e80-c542-11eb-9d65-800a0e8ff092.png)

whith settings:
![image](https://user-images.githubusercontent.com/60747886/120802261-86804a00-c542-11eb-898f-7cf255d3b6a8.png)

Tried with Edge.

Regards

**Comment by francoisno** [comment]
Thanks @msansen-esncf I think `readableColor` is a function from SASS/SCSS, anyways it is not mandatory - thus not a good example to start styling the chat look'n'feel.

I have fixed the given snippet/sample in the documentation: https://github.com/theopenconversationkit/tock-react-kit#styling-your-chat
