### ISSUE TITLE
dev dependancies emotion replaced

### ISSUE THREAD

**Issue by msansen-esncf** [theopenconversationkit/tock-react-kit#75]
Hi Tock team,

While testing tock-sharepoint module, i tried a npm fix audit after npm install. Just to inform you that emotion/core and emotion theming had been replaced by @emotion/react

tried to fix it on a [fork](https://github.com/edbot-dev/tock-react-kit/tree/develop) 

but have troubles for builing:
src/index.ts → build/tock-react-kit.umd.js, build/tock-react-kit.esm.js...
(!) Circular dependencies
src\styles\tockThemeProvider.ts -> src\index.ts -> src\styles\tockThemeProvider.ts
src\index.ts -> src\renderChat.tsx -> src\index.ts

Regards

Mat

**Comment by francoisno** [comment]
Hello @msansen-esncf as a matter of fact @emotion/core is renamed to @emotion/react when upgrading to version 11. For now we stick to emotion v10, is it a requirement for you to upgrade?
Btw I have fixed the circular dependency in !76, yet it is also on _master_but does not prevent the toolkit from working ;)

**Comment by msansen-esncf** [comment]
Hello @francoisno
No requierement for us, it was just to get node modules updated 
Thanks for the bug fix. And for your work to update this react module

Regards
