### ISSUE TITLE
useTock throw an error on empty message

### ISSUE THREAD

**Issue by MikaFima** [theopenconversationkit/tock-react-kit#97]
Hello tock.

This line  https://github.com/theopenconversationkit/tock-react-kit/blob/3bd2e7ba7906d0ee42b20676b3a1e9846627647e/src/useTock.ts#L182 thows his error:
![image](https://user-images.githubusercontent.com/4429126/168842108-a18d047c-d708-4c0d-b62b-9598d2cc3e67.png)

## To reproduce

- Add an empty response on studio:
![image](https://user-images.githubusercontent.com/4429126/168842607-52ed9594-0a73-4bd7-b590-2ee335b8bdd9.png)

- This will returns an "empty" message on POST call:
![image](https://user-images.githubusercontent.com/4429126/168843165-d5d15021-d1b1-4ec8-a4cc-e77f23f3a228.png)

- The second message will make this error appear, and no messages are displayed

Thank you

**Comment by Fabilin** [comment]
Fixed in a90c235c71f3676b69e7be0bb2ab816773e2819f
